name: Docker Image API Call

on:
 push:
  branches: [main]
 workflow_dispatch:
  inputs:
   docker-image:
    description: "Docker image to process"
    required: true
    type: string

jobs:
 process-docker-image:
  runs-on: ubuntu-latest
  steps:
   - name: Call API with Docker Image
     uses: github.com/HAABIZ-GAME/actions@main
     with:
      docker-image: ${{ github.event.inputs.docker-image || 'my-registry/game-server:latest' }}
      api-endpoint: ${{ secrets.API_ENDPOINT }}
      api-key: ${{ secrets.API_KEY }}
